### ISSUE TITLE
java.lang.IllegalStateException: Underflow in restore - more restores than saves

### ISSUE THREAD

**Issue by alex-marochko** [thomsonreuters/RippleDecoratorView#3]
Hi! Thanks for your nice lib. Unfortunately, after updating `google-services` plugins i'm having this error under Android 6.0.1:

`
08-22 13:20:27.281 25067-25067/io.finova.connect.finova E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: io.finova.connect.finova, PID: 25067
                                                                          java.lang.IllegalStateException: Underflow in restore - more restores than saves
                                                                              at android.graphics.Canvas.native_restore(Native Method)
                                                                              at android.graphics.Canvas.restore(Canvas.java:575)
                                                                              at com.thomsonreuters.rippledecoratorview.RippleDecoratorView.draw(RippleDecoratorView.java:292)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16469)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
                                                                              at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
                                                                              at android.view.View.updateDisplayListIfDirty(View.java:16429)
                                                                              at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
                                                                              at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
                                                                              at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
                                                                              at android.view.ViewRootImpl.draw(ViewRootImpl.java:3184)
                                                                              at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2983)
                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2572)
                                                                              at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
                                                                              at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7450)
                                                                              at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                              at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                              at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                              at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

`

**Comment by Pirokar** [comment]
yes, library not working, unfortunately
